name: CI

on: [push, pull_request]

jobs:
  main:
    name: Validate app
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14, 16]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install NPM dependencies
        run: npm ci

      - name: Validate app
        run: npm run validate
        env:
          CI: true
