name: CI

on: [push, pull_request]

jobs:
  main:
    name: Validate app
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10, 12, 14]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install NPM dependencies
        run: npm ci

      - name: Validate app
        run: npm run validate
        env:
          CI: true
